CREATE TABLE USERS(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(255),
  BIO VARCHAR(255),
  EMAIL VARCHAR(255),
  IMAGE VARCHAR(255),
  PASSWORD VARCHAR(255),
  TOKEN VARCHAR(500)
);

CREATE TABLE FOLLOWED_USERS(
  USER_ID BIGINT NOT NULL,
  FOLLOWED_ID BIGINT NOT NULL,
  PRIMARY KEY (USER_ID, FOLLOWED_ID),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT FK_FOLLOWED_ID FOREIGN KEY (FOLLOWED_ID) REFERENCES USERS(ID)
);
